documents:
- name:          Check HTML
  parser:        pyspelling.parsers.html_parser
  options:
    comments:    true
    attributes:
    - title
    - alt
    ignores:
    - code
    - pre
    - a.magiclink-compare
    - a.magiclink-commit
    - span.keys
    - .MathJax_Preview
    - .md-nav__link
    - .md-footer-custom-text
    - .md-source__repository
    - .headerlink
    - .md-icon
  sources:
    - ./*
